In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv(r"C:\Users\USER\Desktop\Machine_Learning_360V2\machine_learning_360v2\modeling\funding_model\synthetic_onboarding_features.csv")
data.head()

,sme_id,revenue,profit_margin,employee_count,sector,age_of_business,late_payments,debt_ratio,marketing_spend,credit_history,...,profit_per_employee,late_payment_rate,debt_profit_ratio,marketing_efficiency,profitability,financial_health,payment_behavior,operational_efficiency,marketing_roi,business_stage
0,1,63049.921922,0.102738,24,services,19,1,0.105927,77.751565,630,...,2627.080080,0.052632,1.031049,810.915146,Thin Margin,Manageable,Reliable,Lean,High ROI,Mature
1,2,47135.917154,0.139884,51,manufacturing,1,1,0.435151,217.953324,586,...,924.233670,1.000000,3.110804,216.266108,Thin Margin,Risky,Occasional,Lean,High ROI,Startup
2,3,68567.289121,0.094531,10,agriculture,20,0,0.520275,87.498739,250,...,6856.728912,0.000000,5.503777,783.637453,Thin Margin,Risky,Reliable,Lean,High ROI,Mature
3,4,123677.627562,0.128443,72,manufacturing,15,0,0.357259,179.523230,458,...,1717.744827,0.000000,2.781464,688.922695,Thin Margin,Manageable,Reliable,Lean,High ROI,Mature
4,5,45495.409067,0.017447,21,beauty,18,1,0.279382,136.857027,467,...,2166.448051,0.055556,16.013231,332.430202,Thin Margin,Risky,Reliable,Lean,High ROI,Mature

In [10]:
data.dtypes.value_counts()

float64    10
object      7
int64       5
Name: count, dtype: int64

In [5]:
data.describe(
)

,sme_id,revenue,profit_margin,employee_count,age_of_business,late_payments,debt_ratio,marketing_spend,credit_history,collateral_value,log_revenue,profit_per_employee,late_payment_rate,debt_profit_ratio,marketing_efficiency
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2.000000e+03,2000.000000,2000.000000,2000.000000,1970.000000,2000.000000
mean,1000.500000,64560.036982,0.149889,50.370000,12.736500,0.263500,0.297757,206.522079,474.403000,1.011205e+04,10.943133,3237.015768,0.038154,3.802581,647.700812
std,577.494589,47477.643644,0.069553,28.548899,6.849637,0.440641,0.144984,195.118077,217.185293,5.833189e+04,0.458625,8355.003067,0.116101,18.006184,1599.358940
min,1.000000,30000.000000,0.000000,1.000000,1.000000,0.000000,0.000000,5.744929,100.000000,1.277129e+01,10.308986,317.691067,0.000000,0.000000,24.269373
25%,500.750000,40247.506821,0.100361,26.000000,7.000000,0.000000,0.196044,85.813365,283.750000,1.087225e+03,10.602828,704.460292,0.000000,1.233203,204.973313
50%,1000.500000,50737.939603,0.149996,51.000000,13.000000,0.000000,0.295229,149.752752,475.500000,3.049799e+03,10.834449,1192.634253,0.000000,1.943834,367.203161
75%,1500.250000,69981.600830,0.196588,75.250000,19.000000,1.000000,0.393946,262.279411,666.000000,8.603480e+03,11.156001,2519.553861,0.043478,3.069265,689.288586
max,2000.000000,1000000.000000,0.424837,99.000000,24.000000,1.000000,0.737555,1777.045663,848.000000,2.467279e+06,13.815512,151848.093553,1.000000,573.276204,55553.835122

In [7]:
data.duplicated().sum()

np.int64(0)

In [11]:
data.columns

Index(['sme_id', 'revenue', 'profit_margin', 'employee_count', 'sector',
       'age_of_business', 'late_payments', 'debt_ratio', 'marketing_spend',
       'credit_history', 'collateral_value', 'log_revenue',
       'profit_per_employee', 'late_payment_rate', 'debt_profit_ratio',
       'marketing_efficiency', 'profitability', 'financial_health',
       'payment_behavior', 'operational_efficiency', 'marketing_roi',
       'business_stage'],
      dtype='object')