In [32]:
import pandas as pd
import numpy as np

data = pd.read_csv(r"C:\Users\USER\Desktop\Machine_Learning_360V2\data\processed\synthetic_onboarding_features.csv")
data.head()

,sme_id,business_name,revenue,profit_margin,debt_ratio,collateral_value,marketing_spend,employee_count,staff_count,age_of_business,...,payroll_to_revenue,marketing_conversion_rate,profitability,financial_health,payment_behavior,operational_efficiency,marketing_roi,business_maturity,customer_base_size,funding_size_category
0,1,SME_1,63049.921922,0.102738,0.170476,560.527308,1592.838126,5,29,17,...,4.832162,0.068517,Thin Margin,Manageable,Problematic,Lean,High ROI,Mature,Large,Large
1,2,SME_2,47135.917154,0.139884,0.295319,1157.020852,23465.149818,10,8,11,...,2.298530,0.114015,Thin Margin,Manageable,Problematic,Lean,Low ROI,Mature,Large,Large
2,3,SME_3,68567.289121,0.094531,0.302703,0.000000,46231.140892,12,44,12,...,2.738567,0.096163,Thin Margin,Risky,Reliable,Lean,Low ROI,Mature,Large,Large
3,4,SME_4,123677.627562,0.128443,0.370895,1310.293284,19879.593466,82,34,3,...,2.835687,0.429293,Thin Margin,Manageable,Problematic,Lean,Moderate ROI,Growth,Medium,Medium
4,5,SME_5,45495.409067,0.017447,0.094971,0.000000,31246.123489,58,17,6,...,7.496825,0.015834,Thin Margin,Risky,Problematic,Lean,Low ROI,Mature,Large,Medium

In [33]:
data.dtypes.value_counts()

float64    30
int64      27
object     18
Name: count, dtype: int64

In [34]:
data.describe(
)

,sme_id,revenue,profit_margin,debt_ratio,collateral_value,marketing_spend,employee_count,staff_count,age_of_business,previous_funding_received,...,debt_profit_ratio,marketing_efficiency,funding_request_ratio,funding_history_score,funding_risk_score,customer_retention_rate,invoice_completion_rate,liquidity_ratio,payroll_to_revenue,marketing_conversion_rate
count,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,...,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000,1960.000000
mean,999.986735,64437.770512,0.152048,0.295393,7140.849472,25396.692435,49.241327,24.834184,12.419388,0.417857,...,3.784186,14.411952,9.702312,2.073968,0.344882,0.756095,0.677127,2.498623,5.149676,0.432900
std,577.286428,47250.563570,0.067625,0.146035,23344.490741,14515.057675,28.618531,14.593717,7.010284,0.493332,...,17.355780,273.986134,6.817542,3.313198,0.260792,0.322553,0.228772,1.508156,3.298765,4.314796
min,1.000000,30000.000000,0.000718,0.000000,0.000000,7.887229,1.000000,0.000000,1.000000,0.000000,...,0.000000,0.672910,0.177833,0.000000,0.000000,0.006462,0.000000,0.115075,0.000000,0.000000
25%,499.750000,40247.506821,0.103886,0.197268,0.000000,12976.100129,23.000000,12.000000,6.000000,0.000000,...,1.189956,1.372107,4.209946,0.000000,0.204119,0.507993,0.566980,1.304427,2.477952,0.049490
50%,997.500000,50791.814833,0.151303,0.296675,1247.931801,25207.153641,50.000000,24.500000,13.000000,0.000000,...,1.962807,2.355090,8.399957,0.000000,0.304238,1.000000,0.717670,2.204033,4.511001,0.095028
75%,1499.250000,69863.271279,0.196952,0.395609,5316.555626,38353.948637,73.000000,38.000000,18.000000,1.000000,...,3.066817,4.950457,14.176269,3.406269,0.411841,1.000000,0.836364,3.449172,7.372597,0.186988
max,2000.000000,1000000.000000,0.424837,0.766937,593375.549170,49983.660262,99.000000,49.000000,24.000000,1.000000,...,500.771465,12049.501137,32.980088,15.822647,1.688186,1.000000,1.000000,7.685381,15.429641,131.000000

In [35]:
data.duplicated().sum()

np.int64(0)

In [36]:
data.columns

Index(['sme_id', 'business_name', 'revenue', 'profit_margin', 'debt_ratio',
       'collateral_value', 'marketing_spend', 'employee_count', 'staff_count',
       'age_of_business', 'sector', 'previous_funding_received',
       'previous_funding_amount', 'default_history', 'loan_applications_count',
       'funding_requested_amount', 'expected_roi', 'project_duration_months',
       'business_stage', 'collateral_offered',
       'business_registration_uploaded', 'tax_clearance_uploaded',
       'financial_statements_uploaded', 'tax_registered', 'tax_paid_last_year',
       'licenses_required', 'licenses_up_to_date', 'total_payroll',
       'cost_per_hire', 'nssf_contribution_percent',
       'nhif_contribution_percent', 'staff_turnover_rate', 'bank_balance',
       'm_pesa_balance', 'pending_invoices', 'paid_invoices', 'late_payments',
       'campaign_spend', 'clicks', 'impressions', 'conversions',
       'target_segment', 'total_customers', 'active_customers',
       'repeat_customers', 'channels_used', 'owner_age', 'owner_gender',
       'education_level', 'employment_status', 'location',
       'eligible_for_funding', 'default_risk', 'business_health_score',
       'log_revenue', 'profit_per_employee', 'late_payment_rate',
       'debt_profit_ratio', 'marketing_efficiency', 'funding_request_ratio',
       'funding_history_score', 'funding_risk_score',
       'customer_retention_rate', 'invoice_completion_rate', 'liquidity_ratio',
       'payroll_to_revenue', 'marketing_conversion_rate', 'profitability',
       'financial_health', 'payment_behavior', 'operational_efficiency',
       'marketing_roi', 'business_maturity', 'customer_base_size',
       'funding_size_category'],
      dtype='object')

In [43]:
data.isnull().sum().sum()

np.int64(0)

In [46]:
print(data['eligible_for_funding'].value_counts())

eligible_for_funding
1    1254
0     706
Name: count, dtype: int64

In [47]:
print(data['default_risk'].value_counts())

default_risk
low       1174
medium     732
high        54
Name: count, dtype: int64