In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\USER\Desktop\Machine_Learning_360V2\data\processed\synthetic_onboarding_data.csv")
df.head()

,sme_id,revenue,profit_margin,employee_count,sector,age_of_business,late_payments,debt_ratio,marketing_spend,credit_history,collateral_value
0,1,63049.921922,0.102738,24,services,19,1,0.105927,77.751565,630,12784.010750
1,2,47135.917154,0.139884,51,manufacturing,1,1,0.435151,217.953324,586,441.472982
2,3,68567.289121,0.094531,10,agriculture,20,0,0.520275,87.498739,250,3657.250605
3,4,123677.627562,0.128443,72,manufacturing,15,0,0.357259,179.523230,458,770.194204
4,5,45495.409067,0.017447,21,beauty,18,1,0.279382,136.857027,467,2013.539032

In [16]:
df.columns

Index(['sme_id', 'revenue', 'profit_margin', 'employee_count', 'sector',
       'age_of_business', 'late_payments', 'debt_ratio', 'marketing_spend',
       'credit_history', 'collateral_value'],
      dtype='object')

In [6]:
df.value_counts()

sme_id  revenue        profit_margin  employee_count  sector         age_of_business  late_payments  debt_ratio  marketing_spend  credit_history  collateral_value
1984    77996.999952   0.071355       36              tech           12               0              0.292053    237.996478       250             7299.668022         1
1983    40202.772698   0.370644       55              transport      15               0              0.515575    333.636129       767             2268.971315         1
1982    34379.198080   0.264843       77              services       2                0              0.220439    434.143980       257             8657.324787         1
1981    36991.155737   0.245379       98              tech           24               0              0.215917    266.311263       583             11644.873959        1
1980    60146.461038   0.076524       73              agriculture    4                0              0.221346    190.697904       761             12722.713362        1
                                                                                                                                                                     ..
5       45495.409067   0.017447       21              beauty         18               1              0.279382    136.857027       467             2013.539032         1
4       123677.627562  0.128443       72              manufacturing  15               0              0.357259    179.523230       458             770.194204          1
3       68567.289121   0.094531       10              agriculture    20               0              0.520275    87.498739        250             3657.250605         1
2       47135.917154   0.139884       51              manufacturing  1                1              0.435151    217.953324       586             441.472982          1
1       63049.921922   0.102738       24              services       19               1              0.105927    77.751565        630             12784.010750        1
Name: count, Length: 2000, dtype: int64

In [8]:
df.shape

(2000, 11)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sme_id            2000 non-null   int64
 1   revenue           2000 non-null   float64
 2   profit_margin     2000 non-null   float64
 3   employee_count    2000 non-null   int64
 4   sector            2000 non-null   object
 5   age_of_business   2000 non-null   int64
 6   late_payments     2000 non-null   int64
 7   debt_ratio        2000 non-null   float64
 8   marketing_spend   2000 non-null   float64
 9   credit_history    2000 non-null   int64
 10  collateral_value  2000 non-null   float64
dtypes: float64(5), int64(5), object(1)
memory usage: 172.0+ KB

In [10]:
df.describe()

,sme_id,revenue,profit_margin,employee_count,age_of_business,late_payments,debt_ratio,marketing_spend,credit_history,collateral_value
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2.000000e+03
mean,1000.500000,64560.036982,0.149889,50.370000,12.736500,0.263500,0.297757,206.522079,474.403000,1.011205e+04
std,577.494589,47477.643644,0.069553,28.548899,6.849637,0.440641,0.144984,195.118077,217.185293,5.833189e+04
min,1.000000,30000.000000,0.000000,1.000000,1.000000,0.000000,0.000000,5.744929,100.000000,1.277129e+01
25%,500.750000,40247.506821,0.100361,26.000000,7.000000,0.000000,0.196044,85.813365,283.750000,1.087225e+03
50%,1000.500000,50737.939603,0.149996,51.000000,13.000000,0.000000,0.295229,149.752752,475.500000,3.049799e+03
75%,1500.250000,69981.600830,0.196588,75.250000,19.000000,1.000000,0.393946,262.279411,666.000000,8.603480e+03
max,2000.000000,1000000.000000,0.424837,99.000000,24.000000,1.000000,0.737555,1777.045663,848.000000,2.467279e+06