In [16]:
import numpy as np
import pandas as pd

In [17]:
df = pd.read_csv(r"C:\Users\USER\Desktop\Machine_Learning_360V2\data\processed\synthetic_sme_agents_data.csv")
df.head()

,sme_id,business_name,revenue,profit_margin,debt_ratio,employee_count,staff_count,age_of_business,sector,previous_funding_received,...,education_level,employment_status,location,previous_funding_amount,default_history,collateral_value,total_payroll,eligible_for_funding,default_risk,business_health_score
0,1,SME_1,63049.921922,0.102738,0.170476,38,11,6,services,0,...,bachelor,employed,Kisumu,0.000000,0,0.000000,98621.376210,0,low,60.2
1,2,SME_2,47135.917154,0.139884,0.295319,41,1,15,retail,0,...,master,employed,Other,0.000000,0,9398.712619,236766.221130,1,low,45.3
2,3,SME_3,68567.289121,0.094531,0.302703,7,12,19,manufacturing,0,...,highschool,self-employed,Mombasa,0.000000,0,2562.026333,241216.061919,1,low,46.2
3,4,SME_4,123677.627562,0.128443,0.370895,78,3,21,services,1,...,phd,employed,Kisumu,254490.943076,0,0.000000,499470.715046,1,low,51.1
4,5,SME_5,45495.409067,0.017447,0.094971,53,19,15,tech,0,...,highschool,employed,Kisumu,0.000000,0,2125.667541,225956.733774,1,low,41.9

In [18]:
df.columns

Index(['sme_id', 'business_name', 'revenue', 'profit_margin', 'debt_ratio',
       'employee_count', 'staff_count', 'age_of_business', 'sector',
       'previous_funding_received', 'loan_applications_count',
       'funding_requested_amount', 'project_duration_months', 'business_stage',
       'collateral_offered', 'tax_registered', 'tax_paid_last_year',
       'licenses_required', 'licenses_up_to_date', 'bank_balance',
       'm_pesa_balance', 'pending_invoices', 'paid_invoices', 'campaign_spend',
       'clicks', 'impressions', 'conversions', 'total_customers',
       'active_customers', 'repeat_customers', 'owner_age', 'owner_gender',
       'education_level', 'employment_status', 'location',
       'previous_funding_amount', 'default_history', 'collateral_value',
       'total_payroll', 'eligible_for_funding', 'default_risk',
       'business_health_score'],
      dtype='object')

In [19]:
df.value_counts()

sme_id  business_name  revenue        profit_margin  debt_ratio  employee_count  staff_count  age_of_business  sector         previous_funding_received  loan_applications_count  funding_requested_amount  project_duration_months  business_stage  collateral_offered  tax_registered  tax_paid_last_year  licenses_required  licenses_up_to_date  bank_balance   m_pesa_balance  pending_invoices  paid_invoices  campaign_spend  clicks  impressions  conversions  total_customers  active_customers  repeat_customers  owner_age  owner_gender  education_level  employment_status  location  previous_funding_amount  default_history  collateral_value  total_payroll  eligible_for_funding  default_risk  business_health_score
2000    SME_2000       38975.656998   0.175245       0.124458    55              12           1                beauty         1                          4                        796637.972823             18                       startup         1                   1               1                   2                  1                    182187.178763  18990.798491    15                6              15826.880916    2102    20945        26           2463             2463              1995              29         male          none             self-employed      Eldoret   153855.341816            0                1560.070835       246681.947271  0                     low           52.9                     1
1       SME_1          63049.921922   0.102738       0.170476    38              11           6                services       0                          8                        961270.156530             3                        startup         0                   1               1                   4                  1                    125225.772093  2737.492153     18                43             30825.067439    3982    5816         315          3821             2501              2481              56         male          bachelor         employed           Kisumu    0.000000                 0                0.000000          98621.376210   0                     low           60.2                     1
2       SME_2          47135.917154   0.139884       0.295319    41              1            15               retail         0                          5                        107841.853924             15                       startup         1                   1               0                   3                  1                    143546.196712  41498.580242    12                32             436.553787      177     41106        427          1491             1491              1449              35         male          master           employed           Other     0.000000                 0                9398.712619       236766.221130  1                     low           45.3                     1
3       SME_3          68567.289121   0.094531       0.302703    7               12           19               manufacturing  0                          2                        689388.900069             5                        growth          1                   1               1                   4                  0                    65115.265410   25817.089324    10                10             39143.203105    2610    37449        239          4737             2516              1852              27         male          highschool       self-employed      Mombasa   0.000000                 0                2562.026333       241216.061919  1                     low           46.2                     1
4       SME_4          123677.627562  0.128443       0.370895    78              3            21               services       1                          2                        963018.796474             27                       growth          0                   1               1                   3                  1                    171501.122086  43183.876987    15                22             47602.591834    4513    65162        413          2277             2277              42                59         male          phd              employed           Kisumu    254490.943076            0                0.000000          499470.715046  1                     low           51.1                     1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ..
13      SME_13         55436.059171   0.096160       0.152251    29              40           19               tech           0                          7                        852618.962781             20                       mature          0                   1               0                   1                  1                    151051.028492  8528.512849     1                 27             31247.920026    1946    65783        132          3940             870               27                29         male          master           employed           Nairobi   0.000000                 0                0.000000          391601.524889  0                     low           53.7                     1
12      SME_12         42125.649524   0.096609       0.089166    52              11           2                services       0                          5                        834824.169560             22                       mature          1                   1               1                   2                  1                    15290.498635   37378.986883    19                18             2622.007529     2004    66389        241          2987             1548              799               43         female        highschool       employed           Other     0.000000                 0                30242.482868      198667.573072  1                     low           46.9                     1
11      SME_11         42155.582499   0.037471       0.303395    16              7            8                agriculture    1                          8                        55093.108529              14                       startup         1                   1               1                   2                  1                    157556.194259  12881.822370    10                9              9638.710189     3529    71588        237          1823             1823              1391              35         male          highschool       self-employed      Eldoret   148817.429898            0                1243.552720       267326.462144  1                     medium        60.2                     1
10      SME_10         64638.199204   0.215630       0.394999    22              28           6                manufacturing  0                          6                        347320.704450             18                       growth          1                   1               1                   2                  1                    9973.981601    15888.804295    15                1              2941.607500     1596    7658         35           3742             1580              1580              35         male          highschool       self-employed      Other     0.000000                 0                1003.317509       441011.051446  1                     medium        52.9                     1
9       SME_9          42077.316408   0.196147       0.226759    38              29           8                manufacturing  0                          0                        246701.746061             21                       growth          1                   1               1                   4                  1                    63849.682372   9625.235153     3                 27             49523.461116    1379    46175        122          4015             206               206               27         male          master           self-employed      Nairobi   0.000000                 0                118.712984        180091.890318  1                     low           59.0                     1
Name: count, Length: 1992, dtype: int64

In [20]:
df.shape

(2000, 42)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   sme_id                     2000 non-null   int64
 1   business_name              2000 non-null   object
 2   revenue                    2000 non-null   float64
 3   profit_margin              2000 non-null   float64
 4   debt_ratio                 2000 non-null   float64
 5   employee_count             2000 non-null   int64
 6   staff_count                2000 non-null   int64
 7   age_of_business            2000 non-null   int64
 8   sector                     2000 non-null   object
 9   previous_funding_received  2000 non-null   int64
 10  loan_applications_count    2000 non-null   int64
 11  funding_requested_amount   2000 non-null   float64
 12  project_duration_months    2000 non-null   int64
 13  business_stage             2000 non-null   object
 14  collateral_offered         2000 non-null   int64
 15  tax_registered             2000 non-null   int64
 16  tax_paid_last_year         2000 non-null   int64
 17  licenses_required          2000 non-null   int64
 18  licenses_up_to_date        2000 non-null   int64
 19  bank_balance               2000 non-null   float64
 20  m_pesa_balance             2000 non-null   float64
 21  pending_invoices           2000 non-null   int64
 22  paid_invoices              2000 non-null   int64
 23  campaign_spend             2000 non-null   float64
 24  clicks                     2000 non-null   int64
 25  impressions                2000 non-null   int64
 26  conversions                2000 non-null   int64
 27  total_customers            2000 non-null   int64
 28  active_customers           2000 non-null   int64
 29  repeat_customers           2000 non-null   int64
 30  owner_age                  2000 non-null   int64
 31  owner_gender               2000 non-null   object
 32  education_level            2000 non-null   object
 33  employment_status          2000 non-null   object
 34  location                   2000 non-null   object
 35  previous_funding_amount    2000 non-null   float64
 36  default_history            2000 non-null   int64
 37  collateral_value           2000 non-null   float64
 38  total_payroll              2000 non-null   float64
 39  eligible_for_funding       2000 non-null   int64
 40  default_risk               1992 non-null   object
 41  business_health_score      2000 non-null   float64
dtypes: float64(11), int64(23), object(8)
memory usage: 656.4+ KB

In [22]:
df.describe()

,sme_id,revenue,profit_margin,debt_ratio,employee_count,staff_count,age_of_business,previous_funding_received,loan_applications_count,funding_requested_amount,...,total_customers,active_customers,repeat_customers,owner_age,previous_funding_amount,default_history,collateral_value,total_payroll,eligible_for_funding,business_health_score
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,64560.036982,0.149889,0.294481,50.575500,24.524000,12.708500,0.393000,4.541000,521444.313846,...,2489.289000,1482.037500,954.983000,39.674500,102807.623673,0.042500,6683.710275,270348.030934,0.657500,50.636650
std,577.494589,47477.643644,0.069553,0.146069,28.698974,14.520153,6.824354,0.488539,2.896466,280059.298581,...,1439.774024,1020.969401,706.997432,11.394932,154765.127782,0.201777,17117.647048,133321.247747,0.474665,9.788569
min,1.000000,30000.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,20599.402452,...,50.000000,20.000000,10.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.800000
25%,500.750000,40247.506821,0.100361,0.196981,26.000000,12.000000,7.000000,0.000000,2.000000,283857.010448,...,1221.750000,606.500000,372.750000,30.000000,0.000000,0.000000,0.000000,153366.792462,0.000000,44.200000
50%,1000.500000,50737.939603,0.149996,0.295469,51.000000,24.000000,13.000000,0.000000,5.000000,523936.805392,...,2464.000000,1324.000000,786.500000,40.000000,0.000000,0.000000,1411.468187,273529.845096,1.000000,50.900000
75%,1500.250000,69981.600830,0.196588,0.394323,76.000000,37.000000,19.000000,1.000000,7.000000,758028.330730,...,3724.250000,2211.000000,1424.250000,49.000000,205380.933310,0.000000,5316.872803,387284.974232,1.000000,57.100000
max,2000.000000,1000000.000000,0.424837,0.766937,99.000000,49.000000,24.000000,1.000000,9.000000,999874.009509,...,4999.000000,3999.000000,2983.000000,59.000000,499970.451062,1.000000,233401.500461,499501.383439,1.000000,84.200000

In [23]:
df.isnull().sum().sum()

np.int64(8)

In [24]:
df.isnull().sum()

sme_id                       0
business_name                0
revenue                      0
profit_margin                0
debt_ratio                   0
employee_count               0
staff_count                  0
age_of_business              0
sector                       0
previous_funding_received    0
loan_applications_count      0
funding_requested_amount     0
project_duration_months      0
business_stage               0
collateral_offered           0
tax_registered               0
tax_paid_last_year           0
licenses_required            0
licenses_up_to_date          0
bank_balance                 0
m_pesa_balance               0
pending_invoices             0
paid_invoices                0
campaign_spend               0
clicks                       0
impressions                  0
conversions                  0
total_customers              0
active_customers             0
repeat_customers             0
owner_age                    0
owner_gender                 0
education_level              0
employment_status            0
location                     0
previous_funding_amount      0
default_history              0
collateral_value             0
total_payroll                0
eligible_for_funding         0
default_risk                 8
business_health_score        0
dtype: int64

In [25]:
df['default_risk'].isnull().sum()

np.int64(8)

In [26]:
df.fillna(0, inplace = True)

In [27]:
df['default_risk'].isnull().sum()

np.int64(0)